# Generated by Django 5.2.14 on 2026-05-30 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('plan_type', models.CharField(choices=[('individual', 'Individual'), ('family_floater', 'Family Floater'), ('senior_citizen', 'Senior Citizen')], max_length=20)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_premium', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('no_claim_streak', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('renewal_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['-start_date', 'policy_number'],
            },
        ),
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('claim_type', models.CharField(choices=[('hospitalization', 'Hospitalization'), ('day_care', 'Day Care'), ('outpatient', 'Outpatient'), ('critical_illness', 'Critical Illness')], max_length=20)),
                ('hospital_name', models.CharField(blank=True, max_length=160)),
                ('date_of_service', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='submitted', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy')),
            ],
            options={
                'ordering': ['-created_at', 'claim_number'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.policyholder'),
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('previous_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_history', to='insurance.policy')),
            ],
            options={
                'verbose_name_plural': 'premium history',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
